Server setup
InFact-coop/YiMovi pull request #13
Opened 2017-05-17 14:22 UTC by emilyb7

First things:
- keystone setup
- database setup
- serves up basic hello world

2017-05-17 18:52 UTC, des-des requested changes

2017-05-17 18:52 UTC, des-des commented on README.md
> +Building a CMS-based website with a catalogue of films from the Chinese medical humanties field.
Can you add the steps to get it running?

2017-05-17 18:52 UTC, des-des commented on models/films.js
> +const types = keystone.Field.Types;
Maybe use the same capitalisation. (`types` -> `Types`)?

2017-05-17 18:52 UTC, des-des commented on models/directors.js
> +  //image: { type: types.CloudinaryImage, publicID: 'slug', autoCleanup: true, },
Do we want this?

2017-05-17 18:52 UTC, des-des commented on models/films.js
> +  //image,
:fire:?

2017-05-17 18:52 UTC, des-des commented on models/genres.js
> +  //image: { type: types.CloudinaryImage, publicID: 'slug', autoCleanup: true, },
again :fire:

2017-05-18 09:53 UTC, emilyb7 commented on README.md
> +Building a CMS-based website with a catalogue of films from the Chinese medical humanties field.
there are steps (not very well written but they're there...)

2017-05-18 09:57 UTC, emilyb7 commented on models/films.js
> +  //image,
just a placeholder until we figure out how to host images

2017-05-18 09:58 UTC, emilyb7 commented on models/directors.js
> +  //image: { type: types.CloudinaryImage, publicID: 'slug', autoCleanup: true, },
again (if i uncomment it breaks everything, because cloudinary isn't configured - but we might need it)

2017-05-18 09:58 UTC, emilyb7 commented on models/films.js
> +const types = keystone.Field.Types;
fixed!

2017-05-18 10:19 UTC, des-des approved these changes

2017-05-18 10:20 UTC, merged