moves setting of colors for views to middleware
InFact-coop/YiMovi pull request #133
Opened 2017-06-23 15:09 UTC by emilyb7

related #122

2017-06-23 15:25 UTC, njsfield approved these changes

2017-06-23 15:30 UTC, njsfield approved these changes

2017-06-25 22:41 UTC, des-des requested changes

2017-06-25 22:41 UTC, des-des commented on routes/middleware.js
> +  const colors = require('./setup/colors.js');
names confusing.
```js
const viewColors = require('./setup/view_colors.js')
```

2017-06-25 22:41 UTC, des-des commented on routes/middleware.js
> +  const route = req.url.split('/')[1];
```js
const viewName=
```

2017-06-25 22:41 UTC, des-des commented on routes/middleware.js
> +  locals.color = Object.keys(colors).indexOf(route) > -1
Okay this is a bit weird
```js
Object.keys(colors).indexOf(route) > -1 ?
```
is equivalent to
```js
colors[route] ?
```
anyway, with new names we come out with
```js
locals.color = viewColors[viewName] || viewColors.default
```
Which actually makes sense.. ?
or
```js
const viewColor = viewColors[viewName]
locals.color = viewColor !== indefined ? viewColor : viewColors.default
```
kinda more robust (empty string is falsy)

2017-06-25 22:41 UTC, des-des commented on routes/setup/colors.js
> +module.exports = {
yh rename this file as above?

2017-06-25 22:41 UTC, des-des commented on templates/views/director_profile.pug
> +  #title-container.pa3.shadow-5.z-1.light-gray(class=`bg-${color}`)
Finally,

Can we change the name of this variable (locals.color) to something more specific?

Something like primaryColor ..?

2017-06-26 11:31 UTC, des-des approved these changes

2017-06-26 11:31 UTC, merged