Contact Form & Additional Styling
InFact-coop/YiMovi pull request #134
Opened 2017-06-23 15:49 UTC by njsfield

Fixes #93 

Overview

- Remove CSS directory nested inside of templates directory
- Add contact partial
- Add email & live url extraction from environment variables (for email sending & site redirection, Note that these have defaults if not provided)
- Add max-width rules in _custom.css 
- Add _alerts styling for flash messages

# Environment Variables Needed
```
export EMAIL=yimovi.EMAIL=yimovi.site@gmail.com
export LIVE_URL=https://yimovi....
```

2017-06-23 15:59 UTC, emilyb7 requested changes
Cool, I also think we should add a line of explanatory text about the form. Not sure what exactly yet. Not blocking this PR, we can do it as a separate issue.

2017-06-23 15:59 UTC, emilyb7 commented on templates/views/contact.pug
> +      .silver 000 0000 0000
since this is wrong and we don't know if the client even wants to have a phone number displayed, I would comment this out for now

2017-06-23 15:59 UTC, emilyb7 commented on templates/views/contact.pug
> +          input(type='text', name='name', placeholder='You name').dib.w-100.bn.bb.bg-light-silver.br2.ma1.f5.pa2.white
typo, your  name :p

2017-06-23 15:59 UTC, emilyb7 commented on templates/views/contact.pug
> +          input(type='text', name='name', placeholder='You name').dib.w-100.bn.bb.bg-light-silver.br2.ma1.f5.pa2.white
also, i would prefer to have explicit labels on the form for accessibility and all that. Even if we hide them.

2017-06-23 15:59 UTC, emilyb7 commented on templates/views/contact.pug
> +      h2.tc.light-gray Contact us
can we make this an h1?

2017-06-23 16:20 UTC, emilyb7 approved these changes

2017-06-25 22:53 UTC, des-des requested changes

2017-06-25 22:53 UTC, des-des commented on css/_alerts.css
> +  padding: 2rem;
same as class `pa4`?

2017-06-25 22:53 UTC, des-des commented on css/_alerts.css
> +.alert-success {
same as `white bg-light-green`?

2017-06-25 22:53 UTC, des-des commented on css/_custom.css
> +.mxwi1 { max-width: 1rem; }
http://tachyons.io/docs/layout/max-widths/ ?

2017-06-25 22:53 UTC, des-des commented on routes/index.js
> +  res.locals.live_host = process.env.LIVE_HOST || 'http://0.0.0.0:3000';
Is `live_host` have meaning beyond `host` / `hostname`?

2017-06-25 22:53 UTC, des-des commented on templates/views/contact.pug
> +      //-
?

2017-06-26 07:28 UTC, njsfield commented on routes/index.js
> +  res.locals.live_host = process.env.LIVE_HOST || 'http://0.0.0.0:3000';
Have changed to;
```
process.env.HOST || 'http://0.0.0.0:3000';
```
And in Heroku

2017-06-26 07:33 UTC, njsfield commented
@emilyb7 reassigning for review for approval after changes, then reassigning to @des-des

2017-06-26 10:03 UTC, emilyb7 approved these changes

2017-06-26 10:17 UTC, njsfield commented
Gotta add a quick change

2017-06-26 10:20 UTC, njsfield commented
Sorry @des-des, ready for review

2017-06-26 10:25 UTC, njsfield commented
Sorry just saw npm debug

2017-06-26 11:49 UTC, des-des approved these changes

2017-06-26 11:50 UTC, merged