Add postinstall, deploy-staging, deploy-production scripts
InFact-coop/YiMovi pull request #135
Opened 2017-06-23 16:09 UTC by njsfield

Related #111

2017-06-23 16:21 UTC, emilyb7 approved these changes

2017-06-25 22:56 UTC, des-des requested changes

2017-06-25 22:56 UTC, des-des commented on package.json
> +    "keystone-nightwatch-e2e": "^0.2.14",
do we use this?

2017-06-25 22:56 UTC, des-des commented on package.json
> +    "selenium-download": "^2.0.10"
do we use this?

2017-06-25 22:56 UTC, des-des commented on package.json
> +    "saucelabs": "^1.4.0",
this?

2017-06-26 07:30 UTC, njsfield commented on package.json
> +    "selenium-download": "^2.0.10"
We do

2017-06-26 07:30 UTC, njsfield commented on package.json
> +    "saucelabs": "^1.4.0",
Not currently so will remove

2017-06-26 07:30 UTC, njsfield commented on package.json
> +    "keystone-nightwatch-e2e": "^0.2.14",
We don't, will remove

2017-06-26 07:33 UTC, njsfield commented
@emilyb7 reassigning for review for approval after changes, then reassigning to @des-des

2017-06-26 10:01 UTC, emilyb7 approved these changes

2017-06-26 11:12 UTC, njsfield commented
@des-des With postinstall script set up, our heroku build fails;
![image](https://user-images.githubusercontent.com/16468314/27536790-93bb7bf2-5a68-11e7-8a31-7b8e075eeff3.png)
Heroku cant seem to locate postcss. I've included it in the package dependencies, but heroku still fails. Any thoughts?

2017-06-26 14:45 UTC, des-des commented
@njsfield @emilyb7 

The problem is caused by npm5 I think. Trying to run `NODE_ENV=production npm i` on a fresh clone with node7, npm5 will fail locally.

I expect the easiest solution is to drop down to npm 4 (and delete package.lock which causes heroku to use npm 5)

2017-06-26 15:00 UTC, emilyb7 commented
@des-des deleting package-lock seems to have worked. I didn't have to drop down the npm version. 

Have also upgraded npm deploy scripts to force push.

2017-06-26 15:13 UTC, des-des approved these changes

2017-06-26 15:14 UTC, merged