Localize DB results in routes
InFact-coop/YiMovi pull request #147
Opened 2017-06-27 09:23 UTC by emilyb7

creates helper function that takes mongo DB results and transforms them with localized data only

based on current locale, with English as default locale

logic for switching locales is coming in a separate PR, so this function is currently not being used anywhere

related #102

2017-06-27 09:31 UTC, njsfield approved these changes

2017-06-27 10:19 UTC, emilyb7 commented
Need to make some changes to this. Turns out `_doc` is available when calling `findOne()` but not when returning an array of results (makes sense). Will update the function to reflect that.

2017-06-27 10:20 UTC, emilyb7 commented
For results that contain an array we can do something like:

```js
const localizedGenres = genres.map(genre => require('../helpers/localizeResults.js')(locals.locale, genre));
```

2017-06-27 11:27 UTC, njsfield commented
@emilyb7 Perhaps you could alter the helper function with array/object checking ;

```javascript

const localize = (locale, dbResults) => {
 // if currentLocale === defaultLocale, do nothing
  // english is default
  if (locale === 'en') return dbResults;

  // keynames in DB that contain translatable content follow pattern 'name___locale'
  const separator = '___';
  const translatableKeyReg = /\_{3}.+$/;

  // gets array of translatable values from DB results
  const translatableFields = Object.keys(dbResults)
    .filter(key => translatableKeyReg.test(key))
    .map(filteredKey => filteredKey.replace(translatableKeyReg, ''));

  // create new results object with relevant data only
  return Object.keys(dbResults)
    .filter(key => {
      const [ type, loc, ] = key.split(separator);
      return translatableFields.indexOf(type) < 0 || loc === locale;
    }) // change key name so that '___LOCALE' part is discarded
    .reduce((a, b) =>
      Object.assign({}, a, { [b.replace(translatableKeyReg, '')] : dbResults[b], }), {});

}


module.exports = (locale, dbResults) => {

  if (dbResults instanceof Array) {
     dbResults.map(dbResult => localize(locals.locale, dbResult));
  }  else {
     localize(locals.locale, dbResults));
  }
    
```

2017-06-27 11:42 UTC, emilyb7 commented
@njsfield ok check again! I've adapted your code above slightly...

2017-06-27 11:53 UTC, njsfield requested changes

2017-06-27 11:53 UTC, njsfield commented on routes/helpers/localize_results.js
> +  return localize(dbResults._doc);
You need to pass in locale

2017-06-27 15:01 UTC, des-des requested changes
Okay logic a bit confusing here, I might be getting mixed up

2017-06-27 15:01 UTC, des-des commented on routes/helpers/localize_results.js
> +  // if currentLocale === defaultLocale, do nothing
I think you should get rid of the idea of a default local.

In one part of you application, you should set a default, then, everywhere else, assume it is set?

Thoughts?

2017-06-27 15:01 UTC, des-des commented on routes/helpers/localize_results.js
> +      return translatableFields.indexOf(type) < 0 || loc === locale;
Why are there 2 conditions here?

What we are saying:

  1. Does the field have a translation? OR
  2. is the field the translation we are looking for?

I think the first condition is unnecessary.

Ie if 2 is true, is there a situation where 1 is false?

2017-06-27 15:15 UTC, emilyb7 commented on routes/helpers/localize_results.js
> +  // if currentLocale === defaultLocale, do nothing
yeah i was thinking the same thing, but being lazy. I'll figure out a better solution :)

2017-06-27 15:42 UTC, emilyb7 commented on routes/helpers/localize_results.js
> +      return translatableFields.indexOf(type) < 0 || loc === locale;
Yeaaah you're kind of right. Took me a while to figure it out. I'm glad I wrote tests. I still think it needs 2 conditions, however the first condition is less complicated now.

2017-06-27 15:47 UTC, emilyb7 commented on routes/helpers/localize_results.js
> +  // if currentLocale === defaultLocale, do nothing
ok i think this is better?

2017-06-28 11:33 UTC, njsfield approved these changes

2017-06-28 18:56 UTC, emilyb7 commented
@des-des just checking you haven't forgotten this one? I don't want to bug you, but this has been awaiting your review since yesterday and in the meantime you've merged 2 other PRs.

2017-06-28 20:34 UTC, des-des commented
@emilyb7 sorry, I think I was generally confused my the assigning going on:

2017-06-28 20:37 UTC, des-des approved these changes

2017-06-28 20:37 UTC, merged

2017-06-28 20:56 UTC, emilyb7 commented
🎉