Locale routing pages
InFact-coop/YiMovi pull request #153
Opened 2017-06-27 13:16 UTC by njsfield

Fixes :
  #101 
  #100 

Awaiting review & merge of #148 first

## Overview

- Populate en/chn.json files with static keys used in views (chn.json has placeholder characters)
- Refactor several view files and mixins for locale support
- Remove titles from injection into views (from routes)

Every view is assigned a key of `__`, containing the corresponding JSON object data (converted to JS object).
Static fields are available via dot notation, and JSON formatting closely resembles view/partial name, to simplify lookups

2017-06-27 15:03 UTC, emilyb7 commented on routes/index.js
> +    if ([ 'en', 'chn', ].includes(locale) != true) {
didn't you put these in the setup file? I guess that's another branch though. Anyway, equality again. 
Or you could just do `(![ 'en', 'chn', ].includes(locale))`, right?

2017-06-27 15:13 UTC, emilyb7 requested changes

2017-06-27 15:13 UTC, emilyb7 commented on templates/partials/header.pug
> +    a(href=`${new_locale_url}` title="Switch to English").no-underline.white.pointer.ph1 SWITCH TO #{locale_flipped_formatted}
this button needs to be translated too!

2017-06-27 15:13 UTC, emilyb7 commented on templates/partials/header.pug
>          include ../partials/logo.svg
the logo is no longer aligned against the edge of the page

2017-06-27 15:13 UTC, emilyb7 commented on templates/partials/header.pug
> +    a(href=`${new_locale_url}` title="Switch to English").no-underline.white.pointer.ph1 SWITCH TO #{locale_flipped_formatted}
also let's make this look better, yeah? I have some ideas of how to style this if you don't...

2017-06-27 15:17 UTC, njsfield commented on templates/partials/header.pug
> +    a(href=`${new_locale_url}` title="Switch to English").no-underline.white.pointer.ph1 SWITCH TO #{locale_flipped_formatted}
What are your suggestions then?

2017-06-27 15:50 UTC, emilyb7 commented on templates/partials/header.pug
> +    a(href=`${new_locale_url}` title="Switch to English").no-underline.white.pointer.ph1 SWITCH TO #{locale_flipped_formatted}
here are a couple of examples off the top of my head:

- keystone's own docs: http://keystonejs.com/docs/
- https://www.theguardian.com/uk

I think we could have it even smaller though. Just a simple switch like `CHN / EN` and whatever locale you're currently viewing, that word is highlighted.

2017-06-27 16:22 UTC, emilyb7 commented
if i'm viewing `en` locale and click on the logo in the header, I now get redirected to the homepage for `chn`

2017-06-27 16:22 UTC, emilyb7 requested changes
see latest comment

2017-06-27 16:27 UTC, njsfield commented
@emilyb7 I cant replicate this. Is this occurring for you in this branch

2017-06-27 21:23 UTC, njsfield commented
Update: imported changes in PR #92

2017-06-28 08:04 UTC, emilyb7 commented
cool, it all seems to be working now. But let's get the smaller PRs merged in before this massive one!

2017-06-28 11:08 UTC, closed without merging