Localise data views
InFact-coop/YiMovi pull request #155
Opened 2017-06-27 14:56 UTC by emilyb7

@njsfield sorry, this is massive.
I've pulled in everything we've done so far to get the dynamic content showing properly in the views. And I've fixed a few small things along the way too. 
Mostly, you just need to look at the routes/views files!

2017-06-28 11:35 UTC, emilyb7 commented
waiting for #162 to be merged first

2017-06-28 19:07 UTC, emilyb7 commented
waiting for #147

2017-06-28 21:00 UTC, emilyb7 commented
@njsfield ready for your review now!

2017-06-28 21:44 UTC, njsfield requested changes
Nice work just some small changes, assign me again when ready

2017-06-28 21:44 UTC, njsfield commented on routes/middleware.js
> +  // Add your own local variables here
Remove redundant comment

2017-06-28 21:44 UTC, njsfield commented on routes/middleware.js
> +  const view = req.url.split('/')[2];
Move back to below line 17 to match comment above it

2017-06-28 21:44 UTC, njsfield commented on routes/views/director_profile.js
> +        locals.title = `${director.name} ${director.name_chn || ''} | YiMovi director profile`;
This title key should be removed, the view builds the title name + static fields from JSON files, see [here](https://github.com/InFact-coop/YiMovi/blob/master/templates/views/director_profile.pug#L24)

2017-06-28 21:44 UTC, njsfield commented on routes/views/genre_profile.js
>        locals.title = `${genre.name} films | YiMovi`;
Same as comment above, title should be removed.

2017-06-28 21:44 UTC, njsfield commented on routes/views/index.js
> +      .where('name' + locals.locale === 'en' ? '' : `___${locals.locale}`).ne(null)
You should import the defaultLocale variable from the locales.js file

2017-06-28 22:37 UTC, njsfield approved these changes

2017-06-28 22:42 UTC, njsfield reviewed
(Accidentally set to approved before)

I'm changing to a general feedback review as I'd like to contribute to this project again later for contingency/next sprints. Assigning to Eoin for review

2017-06-28 22:46 UTC, njsfield commented
Sorry/ I've assigned to you @emilyb7 first to review my comments, you can assign @

2017-06-30 09:23 UTC, njsfield commented
See #163

2017-06-30 15:21 UTC, des-des requested changes

2017-06-30 15:21 UTC, des-des commented on routes/views/director_profile.js
> +        locals.director = require('../helpers/localize_results.js')
Move require to top of file (consistent style)

2017-06-30 15:21 UTC, des-des commented on routes/views/genre_profile.js
> +        locals.genre = require('../helpers/localize_results.js')
move require to top

2017-06-30 15:21 UTC, des-des commented on routes/views/index.js
> +        locals.themes = require('../helpers/localize_results.js')
here also the require

2017-06-30 15:21 UTC, des-des commented on routes/views/theme_profile.js
> +      locals.theme = require('../helpers/localize_results.js')
here

2017-07-03 14:49 UTC, des-des approved these changes

2017-07-03 14:49 UTC, merged