Create csv 2
InFact-coop/YiMovi pull request #157
Opened 2017-06-27 18:47 UTC by emilyb7

Script that takes all json files in `/locales` and transforms them to a `.csv` formatted file which we can send to a translator.
Related #137

2017-06-27 21:49 UTC, njsfield commented
You mention in [the related issue](https://github.com/InFact-coop/YiMovi/issues/137);
>
To make this simpler:
can't have multiline translation strings
no nesting of json more than 1 object deep
no arrays
As a result of which:
need to fix keys for flash messages
create new model for team members with english and chinese names

My pr [here](https://github.com/InFact-coop/YiMovi/pull/153) is a working feature without the shallow-json-restriction outline here. The changes you've put here will lead to a lot of breaking changes for my PR.

Please communicate to me what you'd actually like me to do here!

If you'd like me to review this for the functionality only, just assign me in the issue to check out the branch and not raise a PR

If you'd like me to make changes in my PR to reflect this json structure, let me know so we can discuss it!

2017-06-28 07:31 UTC, njsfield commented
This fails if translation_csv directory does not exist. So you can add the lines at the bottom of the parse_json_csv file;

```javascript
...

if (!fs.existsSync('./translation_csv')){
  fs.mkdirSync('./translation_csv');
}

createCsvFile(csvString);
```

You check out the branch **locale_routing_pages_flat_json** which is branched off my [pr](https://github.com/InFact-coop/YiMovi/pull/153), I've done the following;
- Flattened JSON structure
- Pulled this branch in (and added the above code for checking directory exists
- Moved team member names temporarily to static array in about partial (no model change yet)

2017-06-28 07:33 UTC, emilyb7 commented
@njsfield I know about the issues with the json. Your branch with the json files is already merged into this one and I've fixed the json on this branch only. There wasn't much nested stuff, it's a quick change.

For the team members in the array, I suggest we hardcode these in the template for now.

2017-06-28 07:36 UTC, emilyb7 commented
In  any case, your PR needs to be fixed first. It's far more urgent. Can fix anything else at the end of the project.

2017-06-28 09:32 UTC, njsfield commented
Mr branch is not merged into this one, this only contains 5 changes, primarily the JSON files themselves.

I mentioned above my **locale_routing_pages_flat_json** branch, and the changes made in it.

Do you propose I pull those changes into [my open pr](https://github.com/InFact-coop/YiMovi/pull/153) ?

2017-06-28 10:21 UTC, emilyb7 commented
@njsfield no don't worry about it. Getting this PR merged is not urgent at this stage. #153 is much more important.

2017-06-28 10:29 UTC, emilyb7 commented
And oh yeah, you branch was initially merged in so they have been tested together. I separated out the commits so that it would be easier to merge the PR. The json in this branch has been flattened.

2017-06-30 15:32 UTC, des-des requested changes

2017-06-30 15:32 UTC, des-des commented on lib/parse_json_csv.js
> +const pathToJson = locale => `./locales/${locale}.json`;
path.join?

2017-06-30 15:32 UTC, des-des commented on lib/parse_json_csv.js
> +    .map(innerKey => `${key}.${innerKey}`)
indentation?

2017-07-03 14:49 UTC, des-des approved these changes

2017-07-03 14:50 UTC, des-des commented
@emilyb7 conflicts

2017-07-03 14:57 UTC, emilyb7 commented
@des-des fixed!

2017-07-03 15:07 UTC, merged