Video and slider
InFact-coop/YiMovi pull request #40
Opened 2017-05-24 07:13 UTC by emilyb7

Several improvements to movie profile, related #25 

simple image gallery on movie profile #28 

embedded video + links to videos on external sites #26

2017-05-24 18:26 UTC, des-des requested changes
Okay looking good, have committed tachyons again though..

2017-05-24 18:26 UTC, des-des commented on templates/views/movie_profile.pug
> +          each img in movie.gallery
Okay, so you get the index for free

https://pugjs.org/language/iteration.html

2017-05-24 18:26 UTC, des-des commented on templates/views/movie_profile.pug
> +              .slider-image.fl.ma0.pa0.relative.h-100(style=`width:${100 / movie.gallery.length}%`)
Hmm, can we break this down to smaller components?

Do not know pug so this might not be the solution but quite hard to read

2017-05-25 07:20 UTC, emilyb7 commented on templates/views/movie_profile.pug
> +              .slider-image.fl.ma0.pa0.relative.h-100(style=`width:${100 / movie.gallery.length}%`)
i've tried! hopefully looking better now...

2017-05-25 11:42 UTC, des-des approved these changes

2017-05-25 11:42 UTC, merged